### ISSUE TITLE
E492: Not an editor command: Shortcut ...

### ISSUE THREAD

**Issue by autozimu** [sunaku/vim-shortcut#1]
Maybe I use the plugin wrong, but I keeps getting the above error message when I try define mappings within init.vim file.

Here is a simple vimrc to reproduce the issue:

```vim
call plug#begin('~/.local/share/nvim/plugged')

Plug 'sunaku/vim-shortcut'

call plug#end()

Shortcut fzf files in directory and go to chosen file
    \ nnoremap <silent> <Space>ef :Files<Return>
```

After neovim startup, I can actually use the command to define mapping.

I know the problem might be because of initialization dependency. But I cannot figure out how to workaround the issue.

Any suggestions?

(Other than that, very useful plugin, thanks!)

**Comment by sunaku** [comment]
I don't use vim-plug so I don't know if this will work but try adding this line after `plug#end()`:

```vim
runtime plugin/shortcut.vim
```

I think `plug#end()` modifies Vim's runtimepath so the above line should resolve to this plugin.

You could also try asking in the vim-plug project itself.  :sweat_smile: Sorry I couldn't be of more help, cheers.

**Comment by autozimu** [comment]
It work!

Thanks a lot.
