### ISSUE TITLE
[Request] Details for `CommentUsingFIGlet`

### ISSUE THREAD

**Issue by elzii** [sunaku/vim-shortcut#2]
I would love to see the code for that!

**Comment by sunaku** [comment]
Sure, it's [available in my vimrc's figlet config file]( https://github.com/sunaku/.vim/blob/qwerty/bundle/format/FIGlet.vim ), but I've reproduced it below for your convenience:

```vim
Shortcut comment as ASCII art using FIGlet
      \ nnoremap <silent> <Space>c@ V:call CommentUsingFIGlet()<Return>
      \|vnoremap <silent> <Space>c@ :<C-U>call CommentUsingFIGlet()<Return>

function! CommentUsingFIGlet() abort
  " run figlet and mark beginning of lines
  '<,'>FIGlet
  execute "normal! 0\<C-V>`]I.\<C-C>V`]"

  " comment-out the lines figlet'ed above
  execute "normal \<Plug>NERDCommenterComment"

  " remove the marks at beginning of lines
  execute "normal! f.\<C-V>`]f.x"
endfunction
```

**Comment by elzii** [comment]
This is great, thanks!

For any future viewers: Install [vim-FIGet](https://github.com/fadein/vim-FIGlet) and [figlet](http://www.figlet.org/) (available via `brew`, `apt-get`, etc.
